name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Cache gems
      uses: actions/cache@v2
      env:
        cache-name: cache-gems
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Set bundle config path
      run: |
        bundle config path vendor/bundle
    - name: Lint
      run:  make lint/ruby/autocorrect

  test:
    runs-on: ubuntu-latest
    needs: lint
    services:
      mongo:
        image: mongo
        ports:
        - 27017:27017
      redis:
        image: redis
        ports:
        - 6379:6379

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Cache gems
      uses: actions/cache@v2
      env:
        cache-name: cache-gems
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Set bundle config path
      run: |
        bundle config path vendor/bundle
    - name: Ruby Unit tests
      run: make test/unit/ruby
      env:
        MONGODB_URL: localhost:27017
        REDIS_URL: redis://localhost:6379/0
